# Generated by Django 5.0.4 on 2024-05-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_vet_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vet',
            name='specialty',
            field=models.CharField(choices=[('Medicina interna', 'Medicina interna'), ('Cirugía', 'Cirugía'), ('Dermatología', 'Dermatología'), ('Oftalmología', 'Oftalmología'), ('Odontología', 'Odontología'), ('Oncología', 'Oncología'), ('Ortopedia', 'Ortopedia'), ('Cardiología', 'Cardiología'), ('Neurología', 'Neurología'), ('Reproducción', 'Reproducción')], max_length=16),
        ),
    ]
