name: Say hello

on:
    push:
        branches:
            - develop

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
        echo "Hello, Group 10!"